export enum Role {
    '*' ='*',
    ADMIN = 'ADMIN',
    CLOUD_ADMIN = 'CLOUD_ADMIN',
    MANAGER = 'MANAGER', 
    SALES_REPRESENTATIVE = 'SALES_REPRESENTATIVE',
    EXPERT = 'EXPERT',
    WAREHOUSEMAN = 'WAREHOUSEMAN',
    WAREHOUSE_MANAGER = 'WAREHOUSE MANAGER',
    FITTER = 'FITTER',
    FOREMAN = 'FOREMAN'
}