export enum Role {
    '*' ='*',
    ADMIN = 'ADMIN',
    CLOUD_ADMIN = 'CLOUD_ADMIN',
    MANAGER = 'MANAGER', 
    SALES_REPRESENTATIVE = 'SALES_REPRESENTATIVE',
    SPECIALIST = 'SPECIALIST',
    WAREHOUSE_MAN = 'WAREHOUSE_MAN',
    WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
    FITTER = 'FITTER',
    FOREMAN = 'FOREMAN'
}