// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddTaskTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void manysymbolsaddtasktest() {
    driver.get("https://dev.emontazysta.pl/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("fubwusdaajfmopqwjrq9ofzf[0dAK;DUFISSMDPOAJSAUOIJP3[UJPijiouj[kfxl;gjw-049itr90--233l[p;gp;kjmrf9\';tol2kw43w43qq==-0rrkgtfp;vkre9ti2-3kltefg-]oo[r450tpl;-[f3jk5r12099--kr12043tt13irfvm0-13olltr09-423j132it0203-=-9o40490490494945949905r-=5t6-0320i1\`owmdlkmsdkflp\\gvf\'fds../bgv/e/f./wdfvg,?LNUIKL)O(K:htgporpgki0-4lgds-0=gf4kk3-0tgk43-09f-4g904-i93o0tdvsklpfvdplk[vcxbokm[fdsvbomkdfbmoikdfbmoikdsfgvmoifdsv;llszjkmvckjk>>>???\"\"lr=-");
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.id(":r1:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.id(":r2:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("plannedStart")).click();
    driver.findElement(By.id("plannedStart")).sendKeys("2023-03-25T07:41");
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(3)")).click();
    driver.findElement(By.id("plannedEnd")).click();
    driver.findElement(By.id("plannedEnd")).sendKeys("2024-11-14T08:39");
    {
      WebElement element = driver.findElement(By.id(":r5:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r6:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r7:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r8:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r9:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":ra:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(3)")).click();
  }
  @Test
  public void obscuresymboladdtasktest() {
    driver.get("https://dev.emontazysta.pl/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys(">?><>?\"{}::{{+_+_)(*^#@#^&*(~\`\`\`~)_)(*#$%^&*()_)(*&$%%%%%%%^&&**()_???");
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.id(":r1:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(4)")).click();
    {
      WebElement element = driver.findElement(By.id(":r2:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    driver.findElement(By.id("plannedStart")).click();
    driver.findElement(By.id("plannedStart")).sendKeys("2023-03-25T06:34");
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3)")).click();
    driver.findElement(By.id("plannedEnd")).click();
    driver.findElement(By.id("plannedEnd")).sendKeys("2023-08-03T12:38");
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.id(":r5:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r6:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r7:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r8:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r9:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":ra:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-contained .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void wrongdateaddtasktest() {
    driver.get("https://dev.emontazysta.pl/");
    driver.manage().window().setSize(new Dimension(968, 1020));
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("zlecenie1");
    {
      WebElement element = driver.findElement(By.id(":r1:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.id(":r2:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("plannedStart")).click();
    driver.findElement(By.id("plannedStart")).sendKeys("2023-05-20T18:48");
    driver.findElement(By.cssSelector(".MuiTypography-root:nth-child(6)")).click();
    driver.findElement(By.id("plannedEnd")).click();
    driver.findElement(By.id("plannedEnd")).sendKeys("2023-01-02T07:45");
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(6)")).click();
    {
      WebElement element = driver.findElement(By.id(":r5:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r6:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r7:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r8:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":r9:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.id(":ra:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-\']/div[3]/ul/li[2]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void distantdateaddtasktest() {
    driver.get("https://dev.emontazysta.pl/");
    driver.manage().window().setSize(new Dimension(968, 1020));
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("zlecenie1");
    {
      WebElement element = driver.findElement(By.id(":r1:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.id(":r2:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.id("plannedStart")).click();
    driver.findElement(By.id("plannedStart")).sendKeys("1920-03-14T20:57");
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(4)")).click();
    driver.findElement(By.id("plannedEnd")).click();
    driver.findElement(By.id("plannedEnd")).sendKeys("2137-09-04T21:37");
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.id(":r5:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r6:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r7:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r8:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":r9:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id(":ra:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
  }
}
