package seleniumTests;// Generated by Selenium IDE


import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.WebDriver;

import java.time.Duration;
import java.util.concurrent.TimeUnit;

import java.util.HashMap;
import java.util.Map;

import static java.sql.DriverManager.getDriver;
import static org.junit.Assert.*;
import static seleniumTests.LoginPageTest.edgedriver;

public class AddToolTypeTestSeleniumTest {
  private WebDriver driver;
  private WebDriverWait WaitDriver;
@Before
public void setUp() {
  driver = new EdgeDriver();

  WebDriverManager.edgedriver().setup();

}
@After
public void tearDown(){
  driver.quit();
}
  @Test
  public void addToolTypeTestSelenium() throws InterruptedException {

    // Test name: AddToolTypeTestSelenium
    // Step # | name | target | value
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

    // 1 | open | /login | 
    driver.get("https://dev.emontazysta.pl/login");


    // 2 | setWindowSize | 1936x1048 | 
    // 3 | click | id=:r0: |
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r0:"))).click();


//    driver.findElement(By.id(":r0:")).click();
    // 4 | type | id=:r0: | warehouseManager1
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r0:"))).sendKeys("warehouseManager1");
    // 5 | type | id=:r1: | password
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r1:"))).sendKeys("password");
    // 6 | click | css=.MuiButton-contained |
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-contained"))).click();

    // 7 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root:nth-child(2)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | css=.MuiButtonBase-root:nth-child(3) | 
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root:nth-child(2)"))).click();
    // 9 | mouseOut | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | css=.MuiMenuItem-root:nth-child(2) | 
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiMenuItem-root:nth-child(2)"))).click();
    // 11 | click | id=name | 
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("name"))).click();
    // 12 | type | id=name | screwdriver
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("name"))).sendKeys("screwdriver");
    // 13 | type | id=criticalNumber | 10
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("criticalNumber"))).sendKeys("10");


    // 14 | click | css=.MuiButton-contained | 
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-contained"))).click();


    // 15 | mouseOver | css=.MuiButton-text:nth-child(1) | 
    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-text:nth-child(1)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | click | css=.MuiButton-text:nth-child(1) | 
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-text:nth-child(1)"))).click();
    // 17 | mouseOver | css=.MuiButtonBase-root > .MuiSvgIcon-root |

    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root > .MuiSvgIcon-root")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | click | css=.MuiButtonBase-root > .MuiSvgIcon-root | 
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root > .MuiSvgIcon-root"))).click();
  }
}
