package seleniumTests;// Generated by Selenium IDE


import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;
public class AddToolTypeTestSeleniumTest {
  private WebDriver driver;
@Before
public void setUp() {
  driver = new ChromeDriver();
  WebDriverManager.chromedriver().setup();

}
@After
public void tearDown(){
  driver.quit();
}
  @Test
  public void addToolTypeTestSelenium() throws InterruptedException {

    // Test name: AddToolTypeTestSelenium
    // Step # | name | target | value
    Thread.sleep(3000);
    // 1 | open | /login | 
    driver.get("https://dev.emontazysta.pl/login");
    Thread.sleep(2000);

    // 2 | setWindowSize | 1936x1048 | 
    // 3 | click | id=:r0: |
    driver.findElement(By.id(":r0:")).click();
    // 4 | type | id=:r0: | admin
    driver.findElement(By.id(":r0:")).sendKeys("admin");
    // 5 | type | id=:r1: | password
    driver.findElement(By.id(":r1:")).sendKeys("password");
    // 6 | click | css=.MuiButton-contained | 
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    Thread.sleep(3000);

    // 7 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | css=.MuiButtonBase-root:nth-child(3) | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)")).click();
    // 9 | mouseOut | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | css=.MuiMenuItem-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    // 11 | click | id=name | 
    driver.findElement(By.id("name")).click();
    // 12 | type | id=name | screwdriver
    driver.findElement(By.id("name")).sendKeys("screwdriver");
    // 13 | type | id=criticalNumber | 10
    driver.findElement(By.id("criticalNumber")).sendKeys("10");

    // 14 | click | css=.MuiButton-contained | 
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    Thread.sleep(2000);

    // 15 | mouseOver | css=.MuiButton-text:nth-child(1) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-text:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | click | css=.MuiButton-text:nth-child(1) | 
    driver.findElement(By.cssSelector(".MuiButton-text:nth-child(1)")).click();
    // 17 | mouseOver | css=.MuiButtonBase-root > .MuiSvgIcon-root |
    Thread.sleep(2000);

    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root > .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | click | css=.MuiButtonBase-root > .MuiSvgIcon-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root > .MuiSvgIcon-root")).click();
  }
}
