package seleniumTests;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class AddToolTestSeleniumTest {
  private WebDriver driver;

  @Before
  public void setUp() {
    driver = new EdgeDriver();
    WebDriverManager.edgedriver().setup();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addToolTestSelenium() {
    // Test name: ToolTestSelenium
    // Step # | name | target | value
    // 1 | open | / |
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
    driver.get("https://dev.emontazysta.pl/login");

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r0:"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r0:"))).sendKeys("warehouseManager1");
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r1:"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r1:"))).sendKeys("password");
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-contained"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root:nth-child(3)"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiMenuItem-root:nth-child(2)"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("name"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("name"))).sendKeys("Wiertarka Makita 24EL");
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiSelect-select"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiMenuItem-root:nth-child(3)"))).click();
    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiSelect-select")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiSelect-select"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiMenuItem-root:nth-child(9)"))).click();
    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-contained")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-contained"))).click();
    {
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-text:nth-child(1)"))).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root > .MuiSvgIcon-root > path"))).click();
  }
}
