package seleniumTests;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import seleniumTests.util.BasePage;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ZmianafirmynanieaktywnTest extends BasePage {
  private WebDriver edgedriver = new EdgeDriver();
  public WebDriverWait wait = new WebDriverWait(edgedriver, Duration.ofSeconds(5));


  @Before
  public void setUp() {
    WebDriverManager.edgedriver().setup();

  }
  @After
  public void tearDown() {
    edgedriver.quit();
  }
  @Test
  public void zmianafirmynanieaktywn() throws InterruptedException {
    edgedriver.get(baseUrl);

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("email")));
    WebElement loginElement = edgedriver.findElement(By.name("email"));


    clickElement(loginElement);
    loginElement.sendKeys(getLogin());

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\":r1:\"]")));
    WebElement passwordElement = edgedriver.findElement(By.xpath("//*[@id=\":r1:\"]"));
    passwordElement.sendKeys(getPassword());

    WebElement loginButtonElement = edgedriver.findElement(By.xpath("//*[@id=\"root\"]/div/form/div[3]/div[1]/button"));
    clickElement(loginButtonElement);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButtonBase-root:nth-child(2)")));

    {
      WebElement element = edgedriver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2)"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element).perform();
    }
    edgedriver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2)")).click();
    {
      WebElement element = edgedriver.findElement(By.tagName("body"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element, 0, 0).perform();
    }
    edgedriver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(1)")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(1)")));

    edgedriver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(1)")).click();

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-containedPrimary")));

    {
      WebElement element = edgedriver.findElement(By.cssSelector(".MuiButton-containedPrimary"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-containedPrimary")));

    edgedriver.findElement(By.cssSelector(".MuiButton-containedPrimary")).click();
    {
      WebElement element = edgedriver.findElement(By.tagName("body"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element, 0, 0).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(":r8:")));

    {
      WebElement element = edgedriver.findElement(By.id(":r8:"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiBackdrop-root")));
    Thread.sleep(5000);

    {
      WebElement element = edgedriver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element).release().perform();
    }

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiMenuItem-root:nth-child(3)")));

    edgedriver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-contained")));


    edgedriver.findElement(By.cssSelector(".MuiButton-contained")).click();

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".MuiButton-text:nth-child(1)")));

    {
      WebElement element = edgedriver.findElement(By.cssSelector(".MuiButton-text:nth-child(1)"));
      Actions builder = new Actions(edgedriver);
      builder.moveToElement(element).perform();
    }
    edgedriver.findElement(By.cssSelector(".MuiButton-text:nth-child(1)")).click();


  }
}
