name: Bump version
on:
  push:
    branches:
      - "master"
      - "release_.*"
    paths:
      - "Java/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: release_.*
          tag_prefix: backend_v
          dry_run: true