name: Release&Publish Java Prod

on:
  push:
    tags:
      - 'backend/v*'
    paths:
      - Java/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker image
        uses: docker/build-push-action@v2

        with:
          file: Java/E-montazysta/Dockerfile
          context: Java/E-montazysta
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:latest
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      -
        name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          cluster-type: generic
          # Acceptable values: kubeconfig or service-account or service-principal
          method: service-account
          # Cluster Url
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET_DEV }}
      -
        name: Checkout source code
        uses: actions/checkout@v3
      -
        name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4.9
        with:
          namespace: production
          manifests: |
            Java/E-montazysta/.build/backend-pvc.yaml
            Java/E-montazysta/.build/postgres-deployment.yaml
            Java/E-montazysta/.build/postgres-service.yaml
            Java/E-montazysta/.build/postgres-pvc.yaml
            Java/E-montazysta/.build/deployment.yml
            Java/E-montazysta/.build/ingressroute_prod.yml
            Java/E-montazysta/.build/middleware.yml
            Java/E-montazysta/.build/serverstransport.yml
            Java/E-montazysta/.build/service.yml
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:${{ github.sha }}
          imagepullsecrets: |
            regcred
          strategy: basic
          action: deploy
          token: ${{ github.token }}
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}