name: Release&Publish Java Dev

on:
  push:
    branches:
      - 'master'
    paths:
      - Java/**
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: actions/checkout@v2
      - 
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: backend/v
      - 
        name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - 
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          file: Java/E-montazysta/Dockerfile
          context: Java/E-montazysta
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:latest
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:${{ steps.tag_version.outputs.new_tag }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish:
    needs: [release]
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      -
        name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          cluster-type: generic
          # Acceptable values: kubeconfig or service-account or service-principal
          method: service-account
          # Cluster Url
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET_DEV }}
      - 
        name: Checkout source code
        uses: actions/checkout@v3
      - 
        name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4.9
        with:
          namespace: development
          manifests: |
            Java/E-montazysta/.build/deployment.yml
            Java/E-montazysta/.build/ingressroute_dev.yml
            Java/E-montazysta/.build/middleware.yml
            Java/E-montazysta/.build/serverstransport.yml
            Java/E-montazysta/.build/service.yml
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:${{ needs.build-image.steps.tag_version.outputs.new_tag }}
          imagepullsecrets: |
            regcred
          strategy: basic
          action: deploy
          token: ${{ github.token }}