name: Deploy to Portainer

on:
  push:
    branches:
      - '*'

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - 
        name: Build Docker image
        uses: docker/build-push-action@v2
        
        with:
          file: Java/E-montazysta/Dockerfile
          context: Java/E-montazysta
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:latest
            ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:${{ github.sha }}
          cache: enabled
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  java-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          cluster-type: generic
          # Acceptable values: kubeconfig or service-account or service-principal
          method: service-account
          # Cluster Url
          k8s-url: "https://51.38.130.7:6443"
          k8s-secret: production-deployment-token
          token: ${{ secrets.PRODUCTION_DEPLOYMENT_TOKEN }}
