name: Deploy to Portainer

on:
  push:
    branches:
      - '*'

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - 
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          file: Java/E-montazysta/Dockerfile
          context: Java/E-montazysta
          tags: ${{ secrets.DOCKER_REGISTRY }}/emontazysta/backend:latest
          push: true
          
  java-deploy:
    runs-on: ubuntu-latest
    steps:
      - 
